spring:
  application:
    name: box-dispatch-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/box_dispatch}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
  